In [149]:
import numpy as np
import tensorflow as tf
from tqdm import tqdm

In [150]:
n_nuerons=10
n_instance=100
n_feautures=6
batch_size=10
len_sequence=7


In [151]:
x_t=tf.random.uniform((n_instance,len_sequence,n_feautures))
y_true = tf.random.uniform((n_instance,n_nuerons))


In [152]:
W_x = tf.random.uniform((n_feautures, n_nuerons))
W_y = tf.random.uniform((n_nuerons, n_nuerons))
W=tf.Variable(tf.concat([W_x,W_y],axis=0))
b=tf.Variable(tf.random.uniform((1,n_nuerons)))

In [153]:
def rnn_computation(x_t,y_t_1):
    # print(x_t.shape,y_t_1.shape)
    input_matrix=tf.concat([x_t,y_t_1],axis=1)
    z=tf.matmul(input_matrix,W) + b
    return tf.tanh(z)

In [154]:
def forward_pass(x_t):
    h=x_t.shape[0]
    y_t_1=tf.ones(shape=(h,n_nuerons))
    for i in range(len_sequence):
        feed_to_network=x_t[:,i,:]
        y_t_1=rnn_computation(feed_to_network,y_t_1)
        # print(y_t_1)
    return y_t_1


In [155]:

def compute_loss(ops,y_true):
    loss_fn = tf.keras.losses.CategoricalCrossentropy(from_logits=True)
    loss=loss_fn(ops,y_true)
    return loss
    

In [156]:

n_epochs=10
n_iterations=int(n_instance/batch_size)
optimizer = tf.optimizers.Adam(learning_rate=1.0)
for epoch in range(n_epochs):
    iteration = 0  
    epoch_loss = 0

    with tqdm(total=n_iterations, desc=f"Epoch {epoch+1}/{n_epochs}", unit="batch") as pbar:
        for i in range(n_iterations):
            x_batch = x_t[iteration:iteration + batch_size]

            with tf.GradientTape() as tape:
                ops = forward_pass(x_batch)
                
                loss = compute_loss(ops, y_true[iteration:iteration + batch_size])
                

            gradients = tape.gradient(loss, [W, b])
            print(gradients)
            optimizer.apply_gradients(zip(gradients, [W, b]))

            iteration += batch_size  
            epoch_loss += loss.numpy()  

            pbar.set_postfix(loss=loss.numpy())  
            pbar.update(1)  

     





Epoch 1/10:  70%|███████   | 7/10 [00:00<00:00, 34.80batch/s, loss=-14.1]

[<tf.Tensor: shape=(16, 10), dtype=float32, numpy=
array([[4.07077277e-06, 1.04448573e-05, 1.71763149e-05, 2.25993699e-06,
        1.23802874e-05, 2.89952681e-07, 5.67086181e-06, 7.11507073e-06,
        3.40564038e-05, 4.09537613e-08],
       [4.24236441e-06, 1.23436921e-05, 1.87905462e-05, 2.61762580e-06,
        1.52441125e-05, 2.69014180e-07, 6.69336441e-06, 7.43773580e-06,
        4.44065772e-05, 4.67650700e-08],
       [2.72218563e-06, 7.70879433e-06, 1.24923554e-05, 1.35843243e-06,
        1.13653905e-05, 8.87005811e-08, 4.88308342e-06, 4.43294130e-06,
        3.11121948e-05, 1.01674162e-08],
       [3.68966425e-06, 1.15054363e-05, 1.53257479e-05, 2.31574018e-06,
        1.12078023e-05, 2.73884865e-07, 5.89811543e-06, 6.30159502e-06,
        3.77672986e-05, 4.60906335e-08],
       [3.22444907e-06, 1.17420668e-05, 1.56120113e-05, 1.74719241e-06,
        1.47022056e-05, 1.06015520e-07, 7.00508917e-06, 6.37174389e-06,
        4.55707413e-05, 2.32674111e-08],
       [4.77458570e-06, 

Epoch 1/10: 100%|██████████| 10/10 [00:00<00:00, 33.78batch/s, loss=-14] 


[<tf.Tensor: shape=(16, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>, <tf.Tensor: shape=(1, 10), dtype=float32, numpy=array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>]
[<tf.Tensor: shape=(16, 10), dty

Epoch 2/10:  30%|███       | 3/10 [00:00<00:00, 27.76batch/s, loss=-14.1]

[<tf.Tensor: shape=(16, 10), dtype=float32, numpy=
array([[-5.5885032e-08,  9.6251570e-06, -1.0826996e-09, -1.6342794e-05,
         4.5972020e-06,  0.0000000e+00,  2.1731960e-07,  2.9427158e-06,
         0.0000000e+00,  0.0000000e+00],
       [-8.4643467e-08,  4.5580500e-06, -1.8270617e-09, -2.7577356e-05,
         2.0817067e-06,  0.0000000e+00,  9.6483120e-08,  1.3064740e-06,
         0.0000000e+00,  0.0000000e+00],
       [-5.3315837e-08,  4.1203079e-06, -1.2215918e-09, -1.8438092e-05,
         1.7210078e-06,  0.0000000e+00,  7.6372416e-08,  1.0341558e-06,
         0.0000000e+00,  0.0000000e+00],
       [-4.5776304e-08,  9.5096102e-06, -2.3068161e-10, -3.4862280e-06,
         4.4516200e-06,  0.0000000e+00,  2.0861351e-07,  2.8248271e-06,
         0.0000000e+00,  0.0000000e+00],
       [-6.4637810e-08,  8.9082687e-06, -1.6610435e-09, -2.5069976e-05,
         4.0620712e-06,  0.0000000e+00,  1.8813363e-07,  2.5475099e-06,
         0.0000000e+00,  0.0000000e+00],
       [-8.1509093e-08, 

Epoch 2/10:  40%|████      | 4/10 [00:00<00:00, 27.76batch/s, loss=-14.1]

[<tf.Tensor: shape=(16, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>, <tf.Tensor: shape=(1, 10), dtype=float32, numpy=array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>]
[<tf.Tensor: shape=(16, 10), dty

Epoch 2/10:  90%|█████████ | 9/10 [00:00<00:00, 26.37batch/s, loss=-14.1]

[<tf.Tensor: shape=(16, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>, <tf.Tensor: shape=(1, 10), dtype=float32, numpy=array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>]
[<tf.Tensor: shape=(16, 10), dty

Epoch 2/10: 100%|██████████| 10/10 [00:00<00:00, 23.15batch/s, loss=-14] 

[<tf.Tensor: shape=(16, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>, <tf.Tensor: shape=(1, 10), dtype=float32, numpy=array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>]



Epoch 3/10:  30%|███       | 3/10 [00:00<00:00, 23.44batch/s, loss=-14.1]

[<tf.Tensor: shape=(16, 10), dtype=float32, numpy=
array([[-1.0219963e-09,  2.3747627e-06, -2.9564807e-08, -5.8315186e-07,
         1.4148302e-06,  0.0000000e+00,  0.0000000e+00,  7.8822740e-07,
         0.0000000e+00,  0.0000000e+00],
       [-1.7252044e-09,  1.0543206e-06, -4.9907559e-08, -9.8440296e-07,
         6.2814047e-07,  0.0000000e+00,  0.0000000e+00,  3.4994841e-07,
         0.0000000e+00,  0.0000000e+00],
       [-1.1536858e-09,  8.3456064e-07, -3.3374388e-08, -6.5829403e-07,
         4.9721245e-07,  0.0000000e+00,  0.0000000e+00,  2.7700602e-07,
         0.0000000e+00,  0.0000000e+00],
       [-2.1571506e-10,  2.2796269e-06, -6.2403109e-09, -1.2308718e-07,
         1.3581504e-06,  0.0000000e+00,  0.0000000e+00,  7.5665008e-07,
         0.0000000e+00,  0.0000000e+00],
       [-1.5691808e-09,  2.0558327e-06, -4.5394032e-08, -8.9537582e-07,
         1.2248189e-06,  0.0000000e+00,  0.0000000e+00,  6.8236869e-07,
         0.0000000e+00,  0.0000000e+00],
       [-1.4431771e-09, 

Epoch 3/10:  50%|█████     | 5/10 [00:00<00:00, 23.44batch/s, loss=-14.6]

[<tf.Tensor: shape=(16, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>, <tf.Tensor: shape=(1, 10), dtype=float32, numpy=array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>]
[<tf.Tensor: shape=(16, 10), dty

Epoch 3/10:  90%|█████████ | 9/10 [00:00<00:00, 25.81batch/s, loss=-14]  

[<tf.Tensor: shape=(16, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>, <tf.Tensor: shape=(1, 10), dtype=float32, numpy=array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>]
[<tf.Tensor: shape=(16, 10), dty

Epoch 4/10:  10%|█         | 1/10 [00:00<00:00, 14.92batch/s, loss=-13.8]

[<tf.Tensor: shape=(16, 10), dtype=float32, numpy=
array([[-1.0640176e-10,  6.4316492e-07, -5.3747584e-08, -7.8676834e-08,
         5.4860766e-07,  0.0000000e+00,  0.0000000e+00,  2.6274247e-07,
         0.0000000e+00,  0.0000000e+00],
       [-1.7961395e-10,  2.8554516e-07, -9.0729856e-08, -1.3281225e-07,
         2.4356470e-07,  0.0000000e+00,  0.0000000e+00,  1.1664947e-07,
         0.0000000e+00,  0.0000000e+00],
       [-1.2011217e-10,  2.2602684e-07, -6.0673237e-08, -8.8814751e-08,
         1.9279668e-07,  0.0000000e+00,  0.0000000e+00,  9.2335341e-08,
         0.0000000e+00,  0.0000000e+00],
       [-2.2458459e-11,  6.1739894e-07, -1.1344624e-08, -1.6606496e-08,
         5.2662978e-07,  0.0000000e+00,  0.0000000e+00,  2.5221669e-07,
         0.0000000e+00,  0.0000000e+00],
       [-1.6337007e-10,  5.5678805e-07, -8.2524451e-08, -1.2080100e-07,
         4.7492981e-07,  0.0000000e+00,  0.0000000e+00,  2.2745624e-07,
         0.0000000e+00,  0.0000000e+00],
       [-1.5025162e-10, 

Epoch 4/10:  30%|███       | 3/10 [00:00<00:00, 29.13batch/s, loss=-14.1]

[<tf.Tensor: shape=(16, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>, <tf.Tensor: shape=(1, 10), dtype=float32, numpy=array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>]
[<tf.Tensor: shape=(16, 10), dty

Epoch 4/10:  50%|█████     | 5/10 [00:00<00:00, 29.13batch/s, loss=-14.6]

[<tf.Tensor: shape=(16, 10), dtype=float32, numpy=
array([[-2.8557406e-07,  7.6033306e-05, -8.7896126e-07, -1.0693615e-06,
         2.7884922e-05,  2.0507809e-06,  2.3074551e-06,  5.4363092e-05,
         0.0000000e+00,  1.1277300e-06],
       [-3.2753746e-07,  1.2366092e-04, -1.0081194e-06, -1.2264977e-06,
         4.5352168e-05,  3.3353999e-06,  3.7528559e-06,  8.8416389e-05,
         0.0000000e+00,  1.8341453e-06],
       [-2.4538096e-07,  9.0247740e-05, -7.5525190e-07, -9.1885420e-07,
         3.3098011e-05,  2.4341746e-06,  2.7388342e-06,  6.4526277e-05,
         0.0000000e+00,  1.3385592e-06],
       [-2.1402776e-07,  1.4068476e-04, -6.5875071e-07, -8.0144895e-07,
         5.1595591e-05,  3.7945688e-06,  4.2694942e-06,  1.0058826e-04,
         0.0000000e+00,  2.0866437e-06],
       [-1.2580381e-07,  8.4859821e-05, -3.8720842e-07, -4.7108531e-07,
         3.1122010e-05,  2.2888510e-06,  2.5753218e-06,  6.0673963e-05,
         0.0000000e+00,  1.2586453e-06],
       [-2.5110538e-07, 

Epoch 4/10:  90%|█████████ | 9/10 [00:00<00:00, 20.70batch/s, loss=-14]  

[<tf.Tensor: shape=(16, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>, <tf.Tensor: shape=(1, 10), dtype=float32, numpy=array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>]
[<tf.Tensor: shape=(16, 10), dty

Epoch 5/10:   0%|          | 0/10 [00:00<?, ?batch/s]

[<tf.Tensor: shape=(16, 10), dtype=float32, numpy=
array([[-3.08915636e-11,  3.46319581e-07, -5.39549774e-08,
        -2.85499997e-08,  2.88740864e-07,  0.00000000e+00,
         0.00000000e+00,  1.05096987e-07,  0.00000000e+00,
         0.00000000e+00],
       [-5.21472206e-11,  1.53755096e-07, -9.10799471e-08,
        -4.81944902e-08,  1.28191942e-07,  0.00000000e+00,
         0.00000000e+00,  4.66597854e-08,  0.00000000e+00,
         0.00000000e+00],
       [-3.48721017e-11,  1.21706762e-07, -6.09073538e-08,
        -3.22288152e-08,  1.01471933e-07,  0.00000000e+00,
         0.00000000e+00,  3.69341357e-08,  0.00000000e+00,
         0.00000000e+00],
       [-6.52035197e-12,  3.32445609e-07, -1.13883987e-08,
        -6.02611294e-09,  2.77173569e-07,  0.00000000e+00,
         0.00000000e+00,  1.00886680e-07,  0.00000000e+00,
         0.00000000e+00],
       [-4.74311423e-11,  2.99808960e-07, -8.28428810e-08,
        -4.38358860e-08,  2.49963051e-07,  0.00000000e+00,
         0.00000000

Epoch 5/10:  30%|███       | 3/10 [00:00<00:00, 17.39batch/s, loss=-14.1]


[<tf.Tensor: shape=(16, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>, <tf.Tensor: shape=(1, 10), dtype=float32, numpy=array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>]
[<tf.Tensor: shape=(16, 10), dt

Epoch 5/10:  90%|█████████ | 9/10 [00:00<00:00, 21.50batch/s, loss=-14]  

[<tf.Tensor: shape=(16, 10), dtype=float32, numpy=
array([[-1.65582193e-07,  5.69544682e-05, -9.91862748e-07,
        -6.43165436e-07,  2.31735521e-05,  1.85032877e-06,
         2.03862555e-06,  4.47302627e-05,  0.00000000e+00,
         9.64684773e-07],
       [-1.89913507e-07,  9.26310167e-05, -1.13761109e-06,
        -7.37674782e-07,  3.76895732e-05,  3.00938336e-06,
         3.31563024e-06,  7.27495062e-05,  0.00000000e+00,
         1.56896772e-06],
       [-1.42277329e-07,  6.76021082e-05, -8.52263099e-07,
        -5.52643144e-07,  2.75058483e-05,  2.19624781e-06,
         2.41974681e-06,  5.30925863e-05,  0.00000000e+00,
         1.14503257e-06],
       [-1.24098051e-07,  1.05383093e-04, -7.43366456e-07,
        -4.82029975e-07,  4.28781204e-05,  3.42367116e-06,
         3.77207766e-06,  8.27645927e-05,  0.00000000e+00,
         1.78496032e-06],
       [-7.29438483e-08,  6.35661636e-05, -4.36944845e-07,
        -2.83333378e-07,  2.58637083e-05,  2.06512868e-06,
         2.27528426

Epoch 6/10:  40%|████      | 4/10 [00:00<00:00, 18.27batch/s, loss=-14.1]

[<tf.Tensor: shape=(16, 10), dtype=float32, numpy=
array([[-2.35532600e-11,  2.72108252e-07, -6.54596448e-08,
        -2.31379733e-08,  2.59866795e-07,  0.00000000e+00,
         0.00000000e+00,  1.57645488e-07,  0.00000000e+00,
         0.00000000e+00],
       [-3.97596261e-11,  1.20807570e-07, -1.10500672e-07,
        -3.90585910e-08,  1.15372750e-07,  0.00000000e+00,
         0.00000000e+00,  6.99896816e-08,  0.00000000e+00,
         0.00000000e+00],
       [-2.65882195e-11,  9.56267456e-08, -7.38944621e-08,
        -2.61194213e-08,  9.13247362e-08,  0.00000000e+00,
         0.00000000e+00,  5.54012054e-08,  0.00000000e+00,
         0.00000000e+00],
       [-4.97143993e-12,  2.61207276e-07, -1.38167149e-08,
        -4.88378404e-09,  2.49456207e-07,  0.00000000e+00,
         0.00000000e+00,  1.51330013e-07,  0.00000000e+00,
         0.00000000e+00],
       [-3.61638532e-11,  2.35564187e-07, -1.00507236e-07,
        -3.55262202e-08,  2.24966755e-07,  0.00000000e+00,
         0.00000000

Epoch 6/10: 100%|██████████| 10/10 [00:00<00:00, 21.23batch/s, loss=-14] 


[<tf.Tensor: shape=(16, 10), dtype=float32, numpy=
array([[-1.2771197e-07,  4.8761514e-05, -1.0028285e-06, -5.0961501e-07,
         2.1017502e-05,  1.7578124e-06,  1.9490155e-06,  4.0227871e-05,
         0.0000000e+00,  9.6468477e-07],
       [-1.4647848e-07,  7.9305952e-05, -1.1501883e-06, -5.8449990e-07,
         3.4182965e-05,  2.8589143e-06,  3.1698883e-06,  6.5426793e-05,
         0.0000000e+00,  1.5689677e-06],
       [-1.0973716e-07,  5.7877482e-05, -8.6168552e-07, -4.3788927e-07,
         2.4946725e-05,  2.0864354e-06,  2.3133841e-06,  4.7748472e-05,
         0.0000000e+00,  1.1450326e-06],
       [-9.5715656e-08,  9.0223635e-05, -7.5158488e-07, -3.8193861e-07,
         3.8888775e-05,  3.2524877e-06,  3.6062720e-06,  7.4433796e-05,
         0.0000000e+00,  1.7849603e-06],
       [-5.6260898e-08,  5.4422111e-05, -4.4177560e-07, -2.2450045e-07,
         2.3457369e-05,  1.9618722e-06,  2.1752719e-06,  4.4897821e-05,
         0.0000000e+00,  1.0766724e-06],
       [-1.1229718e-07, 

Epoch 7/10:   0%|          | 0/10 [00:00<?, ?batch/s]

[<tf.Tensor: shape=(16, 10), dtype=float32, numpy=
array([[-1.1227488e-11,  1.9789691e-07, -3.9000991e-08, -1.2015933e-08,
         1.7324452e-07,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
         0.0000000e+00,  0.0000000e+00],
       [-1.8952820e-11,  8.7860059e-08, -6.5836524e-08, -2.0283775e-08,
         7.6915164e-08,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
         0.0000000e+00,  0.0000000e+00],
       [-1.2674207e-11,  6.9546722e-08, -4.4026468e-08, -1.3564248e-08,
         6.0883160e-08,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
         0.0000000e+00,  0.0000000e+00],
       [-2.3698112e-12,  1.8996892e-07, -8.2320266e-09, -2.5362301e-09,
         1.6630413e-07,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
         0.0000000e+00,  0.0000000e+00],
       [-1.7238769e-11,  1.7131941e-07, -5.9882417e-08, -1.8449354e-08,
         1.4997782e-07,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
         0.0000000e+00,  0.0000000e+00],
       [-1.5854514e-11, 

Epoch 7/10:  40%|████      | 4/10 [00:00<00:00, 23.59batch/s, loss=-14.1]

[<tf.Tensor: shape=(16, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>, <tf.Tensor: shape=(1, 10), dtype=float32, numpy=array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>]
[<tf.Tensor: shape=(16, 10), dty

Epoch 7/10:  60%|██████    | 6/10 [00:00<00:00, 24.60batch/s, loss=-14.6]

[<tf.Tensor: shape=(16, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>, <tf.Tensor: shape=(1, 10), dtype=float32, numpy=array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>]


Epoch 7/10: 100%|██████████| 10/10 [00:00<00:00, 21.85batch/s, loss=-14] 


[<tf.Tensor: shape=(16, 10), dtype=float32, numpy=
array([[-2.28561566e-05,  2.74493141e-06,  0.00000000e+00,
         0.00000000e+00,  4.98910083e-07,  0.00000000e+00,
         0.00000000e+00,  1.33049454e-07,  0.00000000e+00,
         0.00000000e+00],
       [-2.78458301e-05,  2.42127635e-06,  0.00000000e+00,
         0.00000000e+00,  4.40083568e-07,  0.00000000e+00,
         0.00000000e+00,  1.17361587e-07,  0.00000000e+00,
         0.00000000e+00],
       [-2.62318845e-05,  2.51704205e-06,  0.00000000e+00,
         0.00000000e+00,  4.57489620e-07,  0.00000000e+00,
         0.00000000e+00,  1.22003442e-07,  0.00000000e+00,
         0.00000000e+00],
       [-2.89513027e-05,  2.08202641e-06,  0.00000000e+00,
         0.00000000e+00,  3.78422527e-07,  0.00000000e+00,
         0.00000000e+00,  1.00917816e-07,  0.00000000e+00,
         0.00000000e+00],
       [-2.67633732e-05,  1.43493753e-06,  0.00000000e+00,
         0.00000000e+00,  2.60809713e-07,  0.00000000e+00,
         0.00000000

Epoch 8/10:   0%|          | 0/10 [00:00<?, ?batch/s]

[<tf.Tensor: shape=(16, 10), dtype=float32, numpy=
array([[-8.75208326e-12,  1.73159791e-07, -3.14340376e-08,
        -9.16016507e-09,  1.15496341e-07,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [-1.47741559e-11,  7.68775479e-08, -5.30629549e-08,
        -1.54630300e-08,  5.12767748e-08,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [-9.87983393e-12,  6.08533810e-08, -3.54844758e-08,
        -1.03405000e-08,  4.05887732e-08,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [-1.84732199e-12,  1.66222804e-07, -6.63485311e-09,
        -1.93345673e-09,  1.10869422e-07,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [-1.34380146e-11,  1.49904480e-07, -4.82640594e-08,
        -1.40645877e-08,  9.99852219e-08,  0.00000000e+00,
         0.00000000

Epoch 8/10:  30%|███       | 3/10 [00:00<00:00, 12.81batch/s, loss=-14.1]

[<tf.Tensor: shape=(16, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>, <tf.Tensor: shape=(1, 10), dtype=float32, numpy=array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>]
[<tf.Tensor: shape=(16, 10), dty

Epoch 8/10:  40%|████      | 4/10 [00:00<00:00, 15.89batch/s, loss=-14.1]

[<tf.Tensor: shape=(16, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>, <tf.Tensor: shape=(1, 10), dtype=float32, numpy=array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>]


Epoch 8/10:  80%|████████  | 8/10 [00:00<00:00, 17.51batch/s, loss=-14.1]

[<tf.Tensor: shape=(16, 10), dtype=float32, numpy=
array([[-1.00431059e-07,  4.09714921e-05, -9.33601200e-07,
        -4.16915015e-07,  1.88614504e-05,  1.72697355e-06,
         1.87060698e-06,  3.54481599e-05,  0.00000000e+00,
         9.37510492e-07],
       [-1.15188804e-07,  6.66362248e-05, -1.07078836e-06,
        -4.78178208e-07,  3.06763504e-05,  2.80875770e-06,
         3.04236391e-06,  5.76530547e-05,  0.00000000e+00,
         1.52477151e-06],
       [-8.62958984e-08,  4.86311146e-05, -8.02201555e-07,
        -3.58236349e-07,  2.23875995e-05,  2.04983121e-06,
         2.22031713e-06,  4.20751967e-05,  0.00000000e+00,
         1.11277814e-06],
       [-7.52695613e-08,  7.58097231e-05, -6.99701445e-07,
        -3.12463214e-07,  3.48994217e-05,  3.19542642e-06,
         3.46119214e-06,  6.55898839e-05,  0.00000000e+00,
         1.73467970e-06],
       [-4.42428494e-08,  4.57277638e-05, -4.11278933e-07,
        -1.83663388e-07,  2.10510279e-05,  1.92745347e-06,
         2.08776078

Epoch 8/10: 100%|██████████| 10/10 [00:00<00:00, 18.87batch/s, loss=-14] 

[<tf.Tensor: shape=(16, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>, <tf.Tensor: shape=(1, 10), dtype=float32, numpy=array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>]



Epoch 9/10:  30%|███       | 3/10 [00:00<00:00, 23.80batch/s, loss=-13.7]

[<tf.Tensor: shape=(16, 10), dtype=float32, numpy=
array([[-8.08612899e-12,  1.48422671e-07, -3.24647758e-08,
        -9.22599952e-09,  1.44370432e-07,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [-1.36499770e-11,  6.58950370e-08, -5.48029142e-08,
        -1.55741624e-08,  6.40959712e-08,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [-9.12806809e-12,  5.21600398e-08, -3.66480286e-08,
        -1.04148175e-08,  5.07359665e-08,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [-1.70675746e-12,  1.42476679e-07, -6.85241330e-09,
        -1.94735250e-09,  1.38586785e-07,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [-1.24155035e-11,  1.28489546e-07, -4.98466619e-08,
        -1.41656695e-08,  1.24981526e-07,  0.00000000e+00,
         0.00000000

Epoch 9/10:  80%|████████  | 8/10 [00:00<00:00, 17.56batch/s, loss=-14.1]

[<tf.Tensor: shape=(16, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>, <tf.Tensor: shape=(1, 10), dtype=float32, numpy=array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>]
[<tf.Tensor: shape=(16, 10), dty

Epoch 9/10: 100%|██████████| 10/10 [00:00<00:00, 19.51batch/s, loss=-14] 


[<tf.Tensor: shape=(16, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>, <tf.Tensor: shape=(1, 10), dtype=float32, numpy=array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>]


Epoch 10/10:  30%|███       | 3/10 [00:00<00:00, 21.77batch/s, loss=-13.7]

[<tf.Tensor: shape=(16, 10), dtype=float32, numpy=
array([[-9.61539182e-12,  1.97896910e-07, -3.80467213e-08,
        -1.07500400e-08,  1.44370432e-07,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [-1.62314849e-11,  8.78600588e-08, -6.42256452e-08,
        -1.81468529e-08,  6.40959712e-08,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [-1.08543851e-11,  6.95467222e-08, -4.29492388e-08,
        -1.21352377e-08,  5.07359665e-08,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [-2.02954255e-12,  1.89968915e-07, -8.03060729e-09,
        -2.26903518e-09,  1.38586785e-07,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [-1.47635463e-11,  1.71319414e-07, -5.84172248e-08,
        -1.65056928e-08,  1.24981526e-07,  0.00000000e+00,
         0.00000000

Epoch 10/10:  30%|███       | 3/10 [00:00<00:00, 21.77batch/s, loss=-14.1]

[<tf.Tensor: shape=(16, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>, <tf.Tensor: shape=(1, 10), dtype=float32, numpy=array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>]


Epoch 10/10:  80%|████████  | 8/10 [00:00<00:00, 20.83batch/s, loss=-14.1]

[<tf.Tensor: shape=(16, 10), dtype=float32, numpy=
array([[-8.6989644e-08,  3.6049001e-05, -8.4446333e-07, -3.6998128e-07,
         1.7312288e-05,  1.7115541e-06,  1.8482044e-06,  3.2038741e-05,
         0.0000000e+00,  9.6468477e-07],
       [-9.9772251e-08,  5.8630263e-05, -9.6855217e-07, -4.2434780e-07,
         2.8156786e-05,  2.7836797e-06,  3.0059284e-06,  5.2107960e-05,
         0.0000000e+00,  1.5689677e-06],
       [-7.4746289e-08,  4.2788364e-05, -7.2560937e-07, -3.1790827e-07,
         2.0548821e-05,  2.0315292e-06,  2.1937262e-06,  3.8028385e-05,
         0.0000000e+00,  1.1450326e-06],
       [-6.5195692e-08,  6.6701621e-05, -6.3289571e-07, -2.7728800e-07,
         3.2033000e-05,  3.1668960e-06,  3.4197406e-06,  5.9281421e-05,
         0.0000000e+00,  1.7849603e-06],
       [-3.8321506e-08,  4.0233837e-05, -3.7201104e-07, -1.6298767e-07,
         1.9322028e-05,  1.9102440e-06,  2.0627576e-06,  3.5758036e-05,
         0.0000000e+00,  1.0766724e-06],
       [-7.6490018e-08, 

Epoch 10/10:  90%|█████████ | 9/10 [00:00<00:00, 22.02batch/s, loss=-14]  

[<tf.Tensor: shape=(16, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>, <tf.Tensor: shape=(1, 10), dtype=float32, numpy=array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>]


Epoch 10/10: 100%|██████████| 10/10 [00:00<00:00, 21.97batch/s, loss=-14]
